// A Pi extension: formats the file an edit/write tool call just touched, so
// every agent's output is always `dart format -l 100`-clean without anyone
// having to remember to run it. This is the Pi-side equivalent of
// tool/hooks/format_changed.dart, which does the same job for Claude Code's
// PostToolUse hook — see that file's header comment.
//
// Hand-written, not generated by tool/sync_ai_config.dart, for the same
// reason tool/hooks/format_changed.dart is hand-written: this is too small
// to be worth a generator, and Pi has no subagent/MCP config for that
// script to render in the first place — see ai/README.md.
//
// Contract: react to the built-in `edit`/`write` tools finishing
// successfully against a `.dart` file, then run `fvm dart format -l 100` on
// that file. This extension must never throw and must never block the tool
// call for long — an unexpected event shape, a failed edit, or a formatting
// problem is a silent no-op, the same rule tool/hooks/format_changed.dart
// follows and for the same reason: a hook that can fail or stall the parent
// tool call over an unrelated formatting problem is worse than no hook at
// all. The `fvm exec` call is bounded by FORMAT_TIMEOUT_MS so a first-run
// SDK download (or a hung process) can never stall the agent's turn
// indefinitely — it just skips formatting that once.
//
// The file-path field is read defensively across a few plausible shapes
// (`input.path`, `input.file_path`, `input.filePath`) because Pi's public
// docs (docs/extensions.md, in Pi's own repository — not this one) do not
// pin down the exact field for the `tool_result` event as of this writing.
// If a future Pi version changes the event shape, the worst case is this
// extension silently stops firing — never that it crashes the agent's
// turn. To make that failure mode at least debuggable, a formattable tool
// event with no resolvable path logs once to stderr instead of failing
// silently forever.
//
// Requires the project to be trusted (`pi --approve`); an untrusted project
// never loads `.pi/extensions/` at all — see Pi's own docs/security.md
// (again, in Pi's repository, not this template's docs/) and this
// template's ai/README.md harness-support table.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const FORMATTABLE_TOOLS = new Set(["edit", "write"]);
const FORMAT_TIMEOUT_MS = 10_000;

function extractDartPath(event: any): string | undefined {
  const input = event?.input ?? {};
  const path: unknown = input.path ?? input.file_path ?? input.filePath ?? event?.path;
  return typeof path === "string" && path.endsWith(".dart") ? path : undefined;
}

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T | undefined> {
  return new Promise((resolve) => {
    const timer = setTimeout(() => resolve(undefined), ms);
    promise.then(
      (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      () => {
        clearTimeout(timer);
        resolve(undefined);
      },
    );
  });
}

export default function (pi: ExtensionAPI) {
  pi.on("tool_result", async (event: any) => {
    try {
      if (!FORMATTABLE_TOOLS.has(event?.toolName)) return;
      // A failed edit/write left the file unchanged (or in an unknown
      // state) — don't run a formatter over it.
      if (event?.isError) return;

      const path = extractDartPath(event);
      if (!path) {
        if (typeof console !== "undefined") {
          console.error(
            `dart-format extension: "${event?.toolName}" event had no recognizable ` +
              "file path — see the field-shape comment at the top of this file.",
          );
        }
        return;
      }

      await withTimeout(pi.exec("fvm", ["dart", "format", "-l", "100", path]), FORMAT_TIMEOUT_MS);
    } catch {
      // Deliberately swallowed — see the file header: this extension must
      // never fail the parent tool call over a formatting problem.
    }
  });
}
