// Renders every per-tool AI configuration file (Claude Code, OpenAI Codex,
// Google Antigravity, OpenCode) from the canonical, tool-neutral source in
// `ai/` plus the skill files in `.agents/skills/`. See `ai/README.md` for
// the full rationale and the exact schema of `ai/agents/*.yaml` and
// `ai/mcp.yaml`.
//
// Pi is deliberately NOT rendered here: it has no subagent or MCP concept
// to target (see ai/README.md), and its formatter hook
// (`.pi/extensions/dart-format.ts`) is hand-written, the same way
// `tool/hooks/format_changed.dart` is hand-written for Claude Code's
// PostToolUse hook rather than generated — both are small enough that a
// generator would add more indirection than it saves.
//
// Usage:
//   fvm dart run tool/sync_ai_config.dart            # write every generated file
//   fvm dart run tool/sync_ai_config.dart --check     # exit 1 if any generated
//                                                      # file would change
//
// `--check` is what `tool/quality_gate.dart` runs — it never writes. A
// human/agent who has changed anything under `ai/` or `.agents/skills/`
// runs the no-flag form to regenerate, then commits the result.
//
// Before rendering anything, every `.agents/skills/*/SKILL.md` is validated
// against the Agent Skills naming spec (see `skillValidationErrors` below)
// — OpenCode silently drops a skill whose `name` fails that regex, and Pi
// only warns, so this check is what catches the mistake at sync time
// instead of at "why isn't my skill showing up" debugging time.
//
// KNOWN LIMITATION: this script re-renders every path it knows how to
// produce today; it does not detect a file that was generated by a past
// version of this script for an agent/skill that has since been deleted
// (no manifest of "previously generated paths" is kept). If you delete an
// `ai/agents/*.yaml` file, manually remove its old `.claude/agents/*.md` /
// `.codex/agents/*.toml` / `.agents/agents/*.md` / `.opencode/agents/*.md`
// counterparts too.
import 'dart:convert';
import 'dart:io';

import 'package:yaml/yaml.dart';

const _generatedNotice =
    'GENERATED FILE — DO NOT EDIT.\n'
    'Source: run `fvm dart run tool/sync_ai_config.dart` after editing the\n'
    'files under ai/ or .agents/skills/. See ai/README.md.';

void main(List<String> args) {
  final checkOnly = args.contains('--check');
  final repoRoot = Directory.current;

  final agents = _loadAgents(Directory('${repoRoot.path}/ai/agents'));
  final mcp = _loadMcp(File('${repoRoot.path}/ai/mcp.yaml'));
  final skillNames = _listSkillNames(Directory('${repoRoot.path}/.agents/skills'));
  final reviewWorkflow = File('${repoRoot.path}/ai/workflows/review.md');

  final skillErrors = <String>[];
  for (final name in skillNames) {
    final skillFile = File('${repoRoot.path}/.agents/skills/$name/SKILL.md');
    if (!skillFile.existsSync()) {
      skillErrors.add('$name: missing SKILL.md');
      continue;
    }
    for (final error in skillValidationErrors(
      folderName: name,
      skillMdContent: skillFile.readAsStringSync(),
    )) {
      skillErrors.add('$name: $error');
    }
  }
  if (skillErrors.isNotEmpty) {
    stderr.writeln(
      'Invalid skill frontmatter (violates the Agent Skills naming spec that '
      "OpenCode enforces and Pi warns on — see ai/README.md's harness-support table):",
    );
    for (final error in skillErrors) {
      stderr.writeln('  - $error');
    }
    exitCode = 1;
    return;
  }

  final outputs = <String, String>{};

  for (final agent in agents) {
    outputs['.claude/agents/${agent.name}.md'] = _renderClaudeAgent(agent);
    outputs['.codex/agents/${agent.name}.toml'] = _renderCodexAgent(agent);
    outputs['.agents/agents/${agent.name}.md'] = _renderAntigravityAgent(agent);
    outputs['.opencode/agents/${agent.name}.md'] = renderOpenCodeAgent(agent);
  }

  outputs['.mcp.json'] = _renderClaudeMcp(mcp);
  outputs['.codex/config.toml'] = _renderCodexConfig(mcp);
  outputs['.agents/mcp_config.json'] = _renderAntigravityMcp(mcp);
  outputs['opencode.jsonc'] = renderOpenCodeConfig(mcp);
  outputs['.opencode/.gitignore'] = renderOpenCodeGitignore();

  outputs['.claude/settings.json'] = _renderClaudeSettings(mcp);
  outputs['.agents/rules/00-core.md'] = _renderCoreRules();

  if (reviewWorkflow.existsSync()) {
    outputs['.agents/workflows/code-review.md'] = _renderAntigravityWorkflow(
      reviewWorkflow.readAsStringSync(),
    );
  }

  // Skill copies: everything under .agents/skills/<name>/ is mirrored
  // verbatim into .claude/skills/<name>/ (Claude Code doesn't read
  // .agents/skills — Codex, Antigravity, OpenCode and Pi all do, natively,
  // so none of those four need a copy).
  final skillCopies = <String, String>{};
  for (final name in skillNames) {
    final sourceDir = Directory('${repoRoot.path}/.agents/skills/$name');
    for (final entity in sourceDir.listSync(recursive: true)) {
      if (entity is! File) continue;
      final relative = entity.path.substring(sourceDir.path.length + 1);
      skillCopies['.claude/skills/$name/$relative'] = entity.readAsStringSync();
    }
  }

  final allOutputs = {...outputs, ...skillCopies};

  if (checkOnly) {
    final drift = <String>[];
    allOutputs.forEach((relativePath, expectedContent) {
      final file = File('${repoRoot.path}/$relativePath');
      if (!file.existsSync()) {
        drift.add('missing: $relativePath');
        return;
      }
      if (file.readAsStringSync() != expectedContent) {
        drift.add('out of date: $relativePath');
      }
    });

    if (drift.isEmpty) {
      stdout.writeln('AI config is in sync (${allOutputs.length} generated files checked).');
      exitCode = 0;
    } else {
      stderr
        ..writeln('AI config is OUT OF SYNC. Run:')
        ..writeln('  fvm dart run tool/sync_ai_config.dart')
        ..writeln('to regenerate, then commit the result. Drifted files:');
      for (final line in drift) {
        stderr.writeln('  - $line');
      }
      exitCode = 1;
    }
    return;
  }

  var written = 0;
  allOutputs.forEach((relativePath, content) {
    final file = File('${repoRoot.path}/$relativePath');
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
    written++;
  });
  stdout.writeln('Wrote $written generated AI config file(s).');
}

// ---------------------------------------------------------------------------
// Agent definitions (ai/agents/*.yaml)
// ---------------------------------------------------------------------------

class AgentDef {
  AgentDef({
    required this.name,
    required this.description,
    required this.access,
    required this.tier,
    required this.skills,
    required this.prompt,
  });

  final String name;
  final String description;
  final String access; // 'read-only' | 'run-only' | 'write'
  final String tier; // 'deep' | 'standard' | 'fast'
  final List<String> skills;
  final String prompt;
}

List<AgentDef> _loadAgents(Directory dir) {
  if (!dir.existsSync()) return const [];
  final files = dir.listSync().whereType<File>().where((f) => f.path.endsWith('.yaml')).toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  return files.map((file) {
    final doc = loadYaml(file.readAsStringSync()) as YamlMap;
    final skillsNode = doc['skills'];
    final skills = skillsNode is YamlList
        ? skillsNode.map((e) => e.toString()).toList()
        : <String>[];
    return AgentDef(
      name: (doc['name'] as String).trim(),
      description: (doc['description'] as String).trim(),
      access: (doc['access'] as String).trim(),
      tier: (doc['tier'] as String).trim(),
      skills: skills,
      prompt: (doc['prompt'] as String).trimRight(),
    );
  }).toList();
}

/// True for an access level that never gets a file-editing tool
/// (`read-only` and `run-only` both render the same restricted Claude/
/// Antigravity tool list — they differ only in Codex's sandbox_mode, where
/// `run-only` still needs filesystem writes for build/test output; see
/// ai/README.md's access mapping table).
bool _hasNoEditingTools(String access) => access == 'read-only' || access == 'run-only';

String _claudeModelFor(String tier) => switch (tier) {
  'deep' => 'opus',
  'standard' => 'sonnet',
  'fast' => 'haiku',
  _ => throw ArgumentError('Unknown tier "$tier" — expected deep|standard|fast'),
};

String _antigravityModelFor(String tier) => switch (tier) {
  'deep' => 'pro',
  'standard' || 'fast' => 'flash',
  _ => throw ArgumentError('Unknown tier "$tier" — expected deep|standard|fast'),
};

String? _codexReasoningEffortFor(String tier) => switch (tier) {
  'deep' => 'high',
  'fast' => 'low',
  'standard' => null, // account default
  _ => throw ArgumentError('Unknown tier "$tier" — expected deep|standard|fast'),
};

// ---------------------------------------------------------------------------
// MCP servers (ai/mcp.yaml)
// ---------------------------------------------------------------------------

class McpServer {
  McpServer({
    required this.name,
    required this.description,
    required this.command,
    required this.args,
    required this.envVarNames,
    required this.enabledByDefault,
  });

  final String name;
  final String description;
  final String command;
  final List<String> args;
  final List<String> envVarNames;
  final bool enabledByDefault;
}

List<McpServer> _loadMcp(File file) {
  if (!file.existsSync()) return const [];
  final doc = loadYaml(file.readAsStringSync()) as YamlMap;
  final servers = doc['servers'] as YamlMap? ?? YamlMap();
  return servers.entries.map((entry) {
    final name = entry.key.toString();
    final value = entry.value as YamlMap;
    final argsNode = value['args'];
    final envNode = value['env'];
    return McpServer(
      name: name,
      description: (value['description'] as String? ?? '').trim(),
      command: (value['command'] as String).trim(),
      args: argsNode is YamlList ? argsNode.map((e) => e.toString()).toList() : <String>[],
      envVarNames: envNode is YamlList ? envNode.map((e) => e.toString()).toList() : <String>[],
      enabledByDefault: value['enabled_by_default'] as bool? ?? false,
    );
  }).toList();
}

// ---------------------------------------------------------------------------
// Skills
// ---------------------------------------------------------------------------

List<String> _listSkillNames(Directory dir) {
  if (!dir.existsSync()) return const [];
  return dir
      .listSync()
      .whereType<Directory>()
      .map((d) => d.path.split(Platform.pathSeparator).last)
      .toList()
    ..sort();
}

// ---------------------------------------------------------------------------
// Claude Code rendering
// ---------------------------------------------------------------------------

String _renderClaudeAgent(AgentDef agent) {
  final buffer = StringBuffer()
    ..writeln('---')
    ..writeln(_yamlCommentBlock(_generatedNotice))
    ..writeln('name: ${agent.name}')
    ..writeln('description: ${_yamlFold(agent.description)}');
  if (_hasNoEditingTools(agent.access)) {
    buffer.writeln('tools: Read, Grep, Glob, Bash');
  }
  // access == 'write' omits `tools:` entirely, which means "inherit every
  // tool the parent session has" — see ai/README.md's access mapping table.
  buffer.writeln('model: ${_claudeModelFor(agent.tier)}');
  if (agent.skills.isNotEmpty) {
    buffer.writeln('skills: [${agent.skills.join(', ')}]');
  }
  buffer
    ..writeln('---')
    ..writeln()
    ..writeln(agent.prompt);
  return buffer.toString();
}

String _renderClaudeMcp(List<McpServer> servers) {
  // No per-server `disabled` key here: Claude Code does not read one from
  // project `.mcp.json` (confirmed against current Claude Code docs/issue
  // tracker — a feature request for exactly this was closed as not
  // implemented). The only thing that actually turns a project MCP server
  // off by default is `.claude/settings.json`'s `disabledMcpjsonServers`,
  // rendered by `_renderClaudeSettings` below — every server is listed here
  // unconditionally and disabled, if at all, from that file instead.
  final map = {
    'mcpServers': {
      for (final server in servers)
        server.name: {
          'command': server.command,
          if (server.args.isNotEmpty) 'args': server.args,
          if (server.envVarNames.isNotEmpty)
            'env': {for (final v in server.envVarNames) v: '\${$v}'},
        },
    },
  };
  return '${const JsonEncoder.withIndent('  ').convert(map)}\n';
}

String _renderClaudeSettings(List<McpServer> servers) {
  final disabledServers = servers.where((s) => !s.enabledByDefault).map((s) => s.name).toList();
  final map = {
    r'$schema': 'https://json.schemastore.org/claude-code-settings.json',
    'hooks': {
      'PostToolUse': [
        {
          'matcher': 'Edit|Write',
          'hooks': [
            {
              'type': 'command',
              'command': r'fvm dart run "${CLAUDE_PROJECT_DIR}/tool/hooks/format_changed.dart"',
            },
          ],
        },
      ],
    },
    // This is the field Claude Code actually reads to turn a project MCP
    // server off by default — see the comment on `_renderClaudeMcp` above.
    if (disabledServers.isNotEmpty) 'disabledMcpjsonServers': disabledServers,
  };
  return '${const JsonEncoder.withIndent('  ').convert(map)}\n';
}

// ---------------------------------------------------------------------------
// Codex rendering
// ---------------------------------------------------------------------------

String _renderCodexAgent(AgentDef agent) {
  final buffer = StringBuffer()
    ..writeln('# $_generatedNotice'.replaceAll('\n', '\n# '))
    ..writeln('name = ${_tomlString(agent.name)}')
    ..writeln('description = ${_tomlMultiline(agent.description)}');
  final effort = _codexReasoningEffortFor(agent.tier);
  if (effort != null) buffer.writeln('model_reasoning_effort = ${_tomlString(effort)}');
  // Codex's sandbox_mode is an OS-level filesystem restriction, not just a
  // missing-editing-tool one — "read-only" blocks every write a subprocess
  // makes too. `run-only` needs `workspace-write` so a command like
  // `flutter test` can still write its build/cache output; see
  // ai/README.md's access mapping table for why this differs from Claude
  // and Antigravity, where read-only vs. run-only render identically.
  switch (agent.access) {
    case 'read-only':
      buffer.writeln('sandbox_mode = "read-only"');
    case 'run-only':
      buffer.writeln('sandbox_mode = "workspace-write"');
    case 'write':
      break; // Codex's own default sandbox already permits this.
    default:
      throw ArgumentError(
        'Unknown access "${agent.access}" — expected read-only|run-only|write',
      );
  }
  buffer.writeln('developer_instructions = ${_tomlMultiline(agent.prompt)}');
  return buffer.toString();
}

String _renderCodexConfig(List<McpServer> servers) {
  final buffer = StringBuffer()
    ..writeln('# $_generatedNotice'.replaceAll('\n', '\n# '))
    ..writeln()
    ..writeln('[agents]')
    ..writeln('enabled = true')
    ..writeln();
  for (final server in servers) {
    buffer
      ..writeln('[mcp_servers.${server.name}]')
      ..writeln('command = ${_tomlString(server.command)}');
    if (server.args.isNotEmpty) {
      final args = server.args.map(_tomlString).join(', ');
      buffer.writeln('args = [$args]');
    }
    if (server.envVarNames.isNotEmpty) {
      final vars = server.envVarNames.map(_tomlString).join(', ');
      buffer.writeln('env_vars = [$vars]');
    }
    // Codex's actual on/off switch is this `enabled` field, not the
    // server's presence/absence in the file — a table with no `enabled`
    // line is treated as enabled, so a comment alone (the previous version
    // of this function) did NOT disable anything: Codex would still try to
    // launch it. See ai/README.md and the GitHub issue confirming `enabled`
    // is the real field name (openai/codex#16439 discussion).
    buffer.writeln('enabled = ${server.enabledByDefault}');
    if (!server.enabledByDefault) {
      buffer
        ..writeln('# Disabled by default — see ai/mcp.yaml. Set enabled = true above')
        ..writeln('# once you have credentials configured.');
    }
    buffer.writeln();
  }
  return buffer.toString();
}

// ---------------------------------------------------------------------------
// Antigravity rendering
// ---------------------------------------------------------------------------

String _renderAntigravityAgent(AgentDef agent) {
  const readOnlyTools = ['view_file', 'grep_search', 'run_command'];
  const writeTools = ['view_file', 'grep_search', 'run_command', 'write_file', 'edit_file'];
  // `run_command` is already in readOnlyTools, so run-only and read-only
  // render identically here — see ai/README.md's access mapping table.
  final tools = agent.access == 'write' ? writeTools : readOnlyTools;

  final buffer = StringBuffer()
    ..writeln('---')
    ..writeln(_yamlCommentBlock(_generatedNotice))
    ..writeln('name: ${agent.name}')
    ..writeln('description: ${_yamlFold(agent.description)}')
    ..writeln('tools: [${tools.join(', ')}]')
    ..writeln('model: ${_antigravityModelFor(agent.tier)}')
    ..writeln('subagent: true');
  if (agent.skills.isNotEmpty) {
    buffer.writeln('skills: [${agent.skills.join(', ')}]');
  }
  buffer
    ..writeln('---')
    ..writeln()
    ..writeln(agent.prompt);
  return buffer.toString();
}

String _renderAntigravityMcp(List<McpServer> servers) {
  final map = {
    'mcpServers': {
      for (final server in servers)
        server.name: {
          'command': server.command,
          if (server.args.isNotEmpty) 'args': server.args,
          if (server.envVarNames.isNotEmpty)
            'env': {for (final v in server.envVarNames) v: '\${$v}'},
          'disabled': !server.enabledByDefault,
        },
    },
  };
  return '${const JsonEncoder.withIndent('  ').convert(map)}\n';
}

// ---------------------------------------------------------------------------
// OpenCode rendering
// ---------------------------------------------------------------------------

/// OpenCode's per-agent `permission` block, keyed off the same `access`
/// levels used for Claude/Codex/Antigravity (public so `tool/test/` can
/// assert the mapping per level — see ai/README.md's access mapping table).
///
/// `read-only`/`run-only` deny `edit` the same way Claude/Antigravity never
/// give those agents an editing tool in the first place. Every level also
/// denies `task` — OpenCode's name for subagent dispatch — because each
/// agent's own prompt already says "do NOT delegate further" (see
/// `ai/agents/*.yaml`); this makes that rule structural instead of
/// instruction-only, the same reasoning `ai/README.md` gives for Codex's
/// `sandbox_mode`. No `model` is set: tiers (`deep`/`standard`/`fast`) have
/// no OpenCode mapping today, so every agent uses the session's own model —
/// see ai/README.md.
Map<String, String> openCodePermissionFor(String access) {
  switch (access) {
    case 'read-only':
    case 'run-only':
      return {'edit': 'deny', 'task': 'deny', 'webfetch': 'deny'};
    case 'write':
      return {'task': 'deny'};
    default:
      throw ArgumentError(
        'Unknown access "$access" — expected read-only|run-only|write',
      );
  }
}

String renderOpenCodeAgent(AgentDef agent) {
  final permission = openCodePermissionFor(agent.access);
  final buffer = StringBuffer()
    ..writeln('---')
    ..writeln(_yamlCommentBlock(_generatedNotice))
    ..writeln('name: ${agent.name}')
    ..writeln('description: ${_yamlFold(agent.description)}')
    ..writeln('mode: subagent')
    ..writeln('permission:');
  for (final entry in permission.entries) {
    buffer.writeln('  ${entry.key}: ${entry.value}');
  }
  buffer
    ..writeln('---')
    ..writeln()
    ..writeln(agent.prompt);
  return buffer.toString();
}

/// `opencode.jsonc` — JSONC (not plain JSON) specifically so the generated
/// notice can be a comment instead of a fake config key; OpenCode's own
/// config loader accepts either extension/syntax. Built by hand rather than
/// through `JsonEncoder`, the same choice `_renderCodexConfig` makes for
/// TOML, because `JsonEncoder` has no way to emit a comment.
///
/// The notice is rendered with `//` line comments, NOT `_yamlCommentBlock`'s
/// `#` — JSONC (like JSON5) only recognizes `//` and `/* */` as comment
/// syntax; a `#`-prefixed line is a parse error, which would make OpenCode
/// reject this entire file (MCP servers and the formatter included) instead
/// of just failing to see a comment.
String renderOpenCodeConfig(List<McpServer> servers) {
  final buffer = StringBuffer()
    ..writeln('{')
    ..writeln('  ${_jsoncCommentBlock(_generatedNotice).replaceAll('\n', '\n  ')}')
    ..writeln(r'  "$schema": "https://opencode.ai/config.json",')
    ..writeln('  "mcp": {');
  for (var i = 0; i < servers.length; i++) {
    final server = servers[i];
    final trailingComma = i == servers.length - 1 ? '' : ',';
    final command = [server.command, ...server.args].map(jsonEncode).join(', ');
    buffer
      ..writeln('    ${jsonEncode(server.name)}: {')
      ..writeln('      "type": "local",')
      ..writeln('      "command": [$command],');
    if (server.envVarNames.isNotEmpty) {
      final environment = server.envVarNames
          .map((v) => '${jsonEncode(v)}: ${jsonEncode('{env:$v}')}')
          .join(', ');
      buffer.writeln('      "environment": {$environment},');
    }
    buffer
      ..writeln('      "enabled": ${server.enabledByDefault}')
      ..writeln('    }$trailingComma');
  }
  buffer
    ..writeln('  },')
    // Runs `dart format` at this repo's 100-column width (not the
    // 80-column default — see the flutter-fvm skill) through `fvm`, the
    // same command tool/hooks/format_changed.dart runs for Claude Code.
    ..writeln('  "formatter": {')
    ..writeln('    "dart": {')
    ..writeln(r'      "command": ["fvm", "dart", "format", "-l", "100", "$FILE"],')
    ..writeln('      "extensions": [".dart"]')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln('}');
  return buffer.toString();
}

/// Mirrors upstream OpenCode's own `.opencode/.gitignore` (node_modules and
/// the package manifests/lockfiles OpenCode generates itself when a project
/// plugin declares npm dependencies) — see ai/README.md.
String renderOpenCodeGitignore() {
  return '${_yamlCommentBlock(_generatedNotice)}\n'
      'node_modules\n'
      'package.json\n'
      'bun.lock\n'
      'package-lock.json\n';
}

// ---------------------------------------------------------------------------
// Skill validation
// ---------------------------------------------------------------------------

final _skillNamePattern = RegExp(r'^[a-z0-9]+(-[a-z0-9]+)*$');

/// Validates a skill's `SKILL.md` frontmatter against the Agent Skills
/// naming spec that OpenCode enforces (silently skipping a non-conforming
/// skill) and Pi warns on — see ai/README.md's harness-support table.
/// Public so `tool/test/` can exercise it directly. Returns one
/// human-readable error string per violation; empty means valid.
List<String> skillValidationErrors({
  required String folderName,
  required String skillMdContent,
}) {
  YamlMap? frontmatter;
  try {
    frontmatter = _extractFrontmatter(skillMdContent);
  } on YamlException catch (e) {
    // A skill author's YAML that fails to parse (an unquoted colon in a
    // description, a duplicate key, ...) must produce one validation error
    // for that skill, not crash the whole generator — every other skill
    // still needs to render. See `main`'s skill-validation loop, which
    // collects errors across all skills before failing.
    return ['malformed YAML frontmatter: ${e.message}'];
  }
  if (frontmatter == null) {
    return ['missing or malformed YAML frontmatter (a leading `---` block)'];
  }

  final errors = <String>[];
  final name = frontmatter['name']?.toString() ?? '';
  final description = frontmatter['description']?.toString() ?? '';

  if (!_skillNamePattern.hasMatch(name)) {
    errors.add(
      'name "$name" must match ${_skillNamePattern.pattern} '
      '(lowercase letters, digits and single hyphens only)',
    );
  }
  if (name.length > 64) {
    errors.add('name "$name" is ${name.length} characters long, must be 64 or fewer');
  }
  if (name != folderName) {
    errors.add('name "$name" must match its folder name "$folderName"');
  }
  if (description.isEmpty) {
    errors.add('description must not be empty');
  } else if (description.length > 1024) {
    errors.add('description is ${description.length} characters long, must be 1024 or fewer');
  }
  return errors;
}

/// Parses the YAML block between a file's opening and closing `---` lines.
/// Returns null if the file doesn't start with `---` on its literal first
/// line, or the block never closes — see `_insertNoticeIntoFrontmatter`'s
/// doc comment for why frontmatter parsers are strict about the opening
/// `---` being the first line.
YamlMap? _extractFrontmatter(String content) {
  final lines = content.split('\n');
  if (lines.isEmpty || lines.first.trim() != '---') return null;
  final end = lines.indexWhere((line) => line.trim() == '---', 1);
  if (end == -1) return null;
  final doc = loadYaml(lines.sublist(1, end).join('\n'));
  return doc is YamlMap ? doc : null;
}

String _renderCoreRules() {
  return '''
---
${_yamlCommentBlock(_generatedNotice)}
description: Core architecture and workflow rules for this repository — always on.
alwaysApply: true
---

# This is a fallback, not the source of truth

The real rules live in [AGENTS.md](../../AGENTS.md) at the repo root (plus
one `AGENTS.md` per package under `packages/`). Antigravity's native
`AGENTS.md` support should make this file redundant in normal use — it
exists only so the core rules are still visible if native loading is ever
unavailable in your setup. If you're reading this because native support
worked, you can ignore this file; AGENTS.md is authoritative either way.

Read `AGENTS.md` in full before writing any code in this repository.
''';
}

/// [reviewWorkflowSource] already starts with its own YAML frontmatter
/// (`---` ... `---`) — the notice is inserted as comment lines just inside
/// that opening `---`, not prepended before it. A frontmatter parser only
/// recognizes the block when `---` is the literal first line of the file;
/// putting anything (even an HTML comment) before it makes every field in
/// the block invisible to that parser.
String _renderAntigravityWorkflow(String reviewWorkflowSource) {
  const notice =
      '$_generatedNotice\nSource: ai/workflows/review.md — edit that file, not this one.';
  return _insertNoticeIntoFrontmatter(reviewWorkflowSource, notice);
}

// ---------------------------------------------------------------------------
// String helpers
// ---------------------------------------------------------------------------

/// Renders [notice] (a multi-line plain-text notice) as YAML comment lines
/// (`# ...`), one per input line — safe to place as the first lines
/// *inside* a frontmatter block, right after the opening `---`. Never place
/// a notice before the opening `---`: a frontmatter parser only recognizes
/// the block when `---` is the literal first line of the file, so anything
/// — even an HTML comment — placed before it silently makes every field in
/// the block invisible to that parser. This is exactly the bug a
/// senior-reviewer audit caught in an earlier version of this file.
String _yamlCommentBlock(String notice) {
  return notice.split('\n').map((line) => '# $line').join('\n');
}

/// Same job as [_yamlCommentBlock], but with `//` line comments instead of
/// `#` — for JSONC output (`renderOpenCodeConfig`). JSONC (like JSON5) only
/// recognizes `//` and `/* */` as comment syntax; a `#`-prefixed line there
/// is a parse error, not just an unrecognized comment.
String _jsoncCommentBlock(String notice) {
  return notice.split('\n').map((line) => '// $line').join('\n');
}

/// Inserts [notice] as a YAML comment block just inside [source]'s existing
/// opening `---`, preserving it as the file's literal first line. Falls
/// back to a leading HTML comment if [source] has no frontmatter to begin
/// with (defensive — every current caller's source does have one).
String _insertNoticeIntoFrontmatter(String source, String notice) {
  final lines = source.split('\n');
  if (lines.isEmpty || lines.first.trim() != '---') {
    return '<!-- ${notice.replaceAll('\n', ' ')} -->\n\n$source';
  }
  return [lines.first, _yamlCommentBlock(notice), ...lines.skip(1)].join('\n');
}

/// Folds a plain-text description onto one YAML scalar line, safely, by
/// using a single-quoted YAML string (single quotes need only '' escaping
/// for an embedded '). Avoids the ambiguity of an unquoted scalar containing
/// a colon.
String _yamlFold(String text) {
  final singleLine = text.replaceAll('\n', ' ').replaceAll(RegExp(' +'), ' ').trim();
  return "'${singleLine.replaceAll("'", "''")}'";
}

/// Renders a TOML basic string. Used for short, single-line values only.
//
// The replacement patterns below are deliberately backslash-escape
// sequences (not raw strings) — mixing raw and non-raw literals in a
// string-escaping routine like this one would make the actual characters
// being matched/inserted harder to see at a glance, not easier.
String _tomlString(String value) {
  final escaped = value
      // Search pattern is a literal backslash; a raw string here would
      // read as an *empty* escape sequence to a skimming reader.
      // ignore: use_raw_strings
      .replaceAll('\\', '\\\\')
      // Same reasoning: '\"' below is the two-character replacement
      // (backslash + quote), clearer written as an escape than raw.
      // ignore: use_raw_strings
      .replaceAll('"', '\\"')
      // Replacement is the two-character escape sequence '\n', not a
      // literal newline — clearer spelled out than as a raw string.
      // ignore: use_raw_strings
      .replaceAll('\n', '\\n')
      // Same reasoning for the tab escape.
      // ignore: use_raw_strings
      .replaceAll('\t', '\\t');
  return '"$escaped"';
}

/// Renders a TOML multi-line literal string (`'''...'''`), which preserves
/// the text completely raw — no escaping needed for quotes, backslashes or
/// newlines. Falls back to an escaped basic string in the (very unlikely)
/// case the content itself contains a `'''` sequence, since that would
/// otherwise prematurely close the literal string.
String _tomlMultiline(String value) {
  if (!value.contains("'''")) {
    return "'''\n$value\n'''";
  }
  return _tomlString(value);
}
