// A Claude Code PostToolUse hook: formats the file an Edit/Write tool call
// just touched, so every agent's output is always `dart format -l
// 100`-clean without anyone having to remember to run it.
//
// Contract (see .claude/settings.json's PostToolUse.command, generated by
// tool/sync_ai_config.dart from ai/agents — the hook wiring itself is
// hand-written here, not generated): Claude Code pipes a JSON object on
// stdin with a `tool_input.file_path` field naming the file that was just
// edited/written. If that path ends in `.dart`, this script formats it in
// place. Any other file is a silent no-op (exit 0) — this hook must never
// fail the parent tool call just because a non-Dart file was edited, or
// because formatting hits an unrelated problem.
//
// Codex has no equivalent hook wired today — its config has no hooks
// mechanism this generator targets. OpenCode gets the same "format after
// edit" behavior through its own idiomatic `formatter.dart` config entry in
// generated `opencode.jsonc` instead of this script, and Pi through
// `.pi/extensions/dart-format.ts` — both self-contained, tool-native
// equivalents rather than callers of this file. See ai/README.md.
//
// Written as a Dart script (not a shell script) specifically so it behaves
// identically on macOS, Linux and Windows — see AGENTS.md section 5.
//
// Usage: fvm dart run tool/hooks/format_changed.dart < hook_payload.json
import 'dart:convert';
import 'dart:io';

Future<void> main() async {
  final input = await stdin.transform(utf8.decoder).join();
  if (input.trim().isEmpty) return;

  String? filePath;
  try {
    final decoded = jsonDecode(input);
    if (decoded is Map<String, dynamic>) {
      final toolInput = decoded['tool_input'];
      if (toolInput is Map<String, dynamic>) {
        final rawPath = toolInput['file_path'];
        if (rawPath is String) filePath = rawPath;
      }
    }
  } on Object catch (_) {
    // Deliberately broad: malformed/unexpected payload shape must never
    // fail the parent tool call over a hook-payload parsing issue.
    return;
  }

  if (filePath == null || !filePath.endsWith('.dart')) return;
  if (!File(filePath).existsSync()) return;

  try {
    // `fvm` is intentionally NOT shelled out to here: a hook runs in a
    // minimal, possibly-non-interactive shell where `fvm`'s shim resolution
    // can be flaky. Instead of a bare `'dart'` (which would resolve whatever
    // build happens to be first on PATH, defeating the FVM pin — see
    // AGENTS.md section 5), this runs `Platform.resolvedExecutable`: the
    // exact `dart` binary already running this very script, which Claude
    // Code invoked via `fvm dart run ...` — so it's the FVM-pinned SDK
    // without going through the `fvm` shim a second time.
    await Process.run(Platform.resolvedExecutable, ['format', '-l', '100', filePath]);
  } on Object catch (_) {
    // Deliberately broad: formatting is a courtesy, not a gate —
    // quality_gate.dart is the real enforcement. Never throw out of a hook.
  }
}
